### ISSUE TITLE
Error "toString()"

### ISSUE THREAD

**Issue by hugoalexmartins** [ds300/patch-package#101]
Hey,

I am trying to generate a patch from a fork which I am using and I am receiving this error:

☑ Creating temporary folder
☑ Building clean node_modules with yarn
☑ Diffing your files with clean files
Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at Object.makePatch [as default] (/Users/hugomartins/projectos/visaexpress/visaExpress/node_modules/patch-package/dist/makePatch.js:94:19)
    at /Users/hugomartins/projectos/visaexpress/visaExpress/node_modules/patch-package/dist/index.js:26:32
    at Array.forEach (native)
    at Object.<anonymous> (/Users/hugomartins/projectos/visaexpress/visaExpress/node_modules/patch-package/dist/index.js:25:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
/Users/hugomartins/projectos/visaexpress/visaExpress/node_modules/patch-package/dist/makePatch.js:113
        throw e;
        ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at Object.makePatch [as default] (/Users/hugomartins/projectos/visaexpress/visaExpress/node_modules/patch-package/dist/makePatch.js:94:19)
    at /Users/hugomartins/projectos/visaexpress/visaExpress/node_modules/patch-package/dist/index.js:26:32
    at Array.forEach (native)
    at Object.<anonymous> (/Users/hugomartins/projectos/visaexpress/visaExpress/node_modules/patch-package/dist/index.js:25:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error Command failed with exit code 1.

Any reason for this ?

**Comment by ds300** [comment]
Seems like that might happen when the buffer is too big. If you upgrade to node 10 you might see a more helpful error message.

I should probably avoid the .toString and just pass the buffer directly to writeFileSync
