### ISSUE TITLE
Make patch fails on package lock file dependencies check. 

### ISSUE THREAD

**Issue by olgagiza-home24** [ds300/patch-package#164]
Hello :) I found an issue with TypeError when I am trying to create a patch:
```
$ patch-package apollo-link-maxage
patch-package 6.1.2
• Creating temporary folder
TypeError: Cannot read property 'dependencies' of undefined
    at Object.getPackageResolution (***/node_modules/patch-package/dist/getPackageResolution.js:71:36)
    at Object.makePatch (***/node_modules/patch-package/dist/makePatch.js:49:66)
    at ***/node_modules/patch-package/dist/index.js:48:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (***/node_modules/patch-package/dist/index.js:47:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
***/node_modules/patch-package/dist/makePatch.js:150
        throw e;
        ^
```

I think, nested properties should be check if they exists.
```
at Object.getPackageResolution (***/node_modules/patch-package/dist/getPackageResolution.js:71:36)
return (relevantStackEntry.dependencies[packageDetails.name].resolved ||
            relevantStackEntry.dependencies[packageDetails.name].from);
```

When the patch is created everything seems to work as expected.

**Comment by gabrielmoncea** [comment]
@olgagiza-home24 how did you fix this?

**Comment by Dawqss** [comment]
so I had package.json yarn.lock and package-lock.json, in package-lock.json package to patch was missing (odd).
I just deleted yarn.lock and package-lock.json and run again yarn patch some-package and it worked :)

**Comment by Hew007** [comment]
--use-yarn or deleting
package-lock.json

**Comment by formaldehydeson** [comment]
anyone still landing on this page (I got here after googling a similar error) the root cause of this is here https://github.com/ds300/patch-package/issues/393
