### ISSUE TITLE
Applying Patch Fails When node_modules Directory Is A Symlink

### ISSUE THREAD

**Issue by lots0logs** [ds300/patch-package#200]
Title pretty much explains the issue. If the node_modules directory is a symlink, the patches always fail to apply. Is this intended behavior? Is there a way to get around it?

**Comment by ds300** [comment]
hmm this is not the intended behaviour, I can't think of a reason why patch-package shouldn't support a symlinked node_modules at patch application time. thanks for flagging! 🙏

**Comment by Maxim-Mazurok** [comment]
I'm having related issue trying to use `patch-package` after `npm link X`:

```
maxim@64QHKR3:~/WebWatcher/Frontend2$ npx patch-package orval --include dist
patch-package 7.0.0
• Creating temporary folder
TypeError: Cannot read properties of undefined (reading 'dependencies')
    at Object.getPackageResolution (/home/maxim/WebWatcher/Frontend2/node_modules/patch-package/dist/getPackageResolution.js:98:40)
    at Object.makePatch (/home/maxim/WebWatcher/Frontend2/node_modules/patch-package/dist/makePatch.js:52:63)
    at /home/maxim/WebWatcher/Frontend2/node_modules/patch-package/dist/index.js:53:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/maxim/WebWatcher/Frontend2/node_modules/patch-package/dist/index.js:52:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
/home/maxim/WebWatcher/Frontend2/node_modules/patch-package/dist/makePatch.js:218
        throw e;
        ^

TypeError: Cannot read properties of undefined (reading 'dependencies')
    at Object.getPackageResolution (/home/maxim/WebWatcher/Frontend2/node_modules/patch-package/dist/getPackageResolution.js:98:40)
    at Object.makePatch (/home/maxim/WebWatcher/Frontend2/node_modules/patch-package/dist/makePatch.js:52:63)
    at /home/maxim/WebWatcher/Frontend2/node_modules/patch-package/dist/index.js:53:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/maxim/WebWatcher/Frontend2/node_modules/patch-package/dist/index.js:52:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

Basically I want to create a patch between linked local version and npm version. As a workaround I'm going to copy-paster symlinked package folder.
