### ISSUE TITLE
./integration-tests/yarn-workspaces/yarn-workspaces.test.ts fails

### ISSUE THREAD

**Issue by gomain** [ds300/patch-package#255]
Running `yarn test .*/integration-tests/yarn-workspaces/yarn-workspaces.test.ts` produces these results.
```
yarn run v1.22.4
$ ./run-tests.sh --runInBand ./integration-tests/yarn-workspaces/yarn-workspaces.test.ts
$ rimraf dist patch-package.test*.tgz
$ tsc --project tsconfig.build.json
info Current version: 6.2.2
info New version: 0.0.0
$ rimraf dist/**/*.test.js
info Current version: 0.0.0
info New version: 6.2.2
$ /home/joe/patch-package/node_modules/.bin/jest --runInBand ./integration-tests/yarn-workspaces/yarn-workspaces.test.ts
FAIL integration-tests/yarn-workspaces/yarn-workspaces.test.ts (20.051s)
  Test yarn-workspaces:
    ✕ should exit with 0 status (7ms)
    ✓ should produce output (1ms)
    ✓ should not produce any snapshots (1ms)

  ● Test yarn-workspaces: › should exit with 0 status

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      45 | 
      46 |     it("should exit with 0 status", () => {
    > 47 |       expect(result.status).toBe(0)
         |                             ^
      48 |     })
      49 | 
      50 |     const output = result.stdout.toString() + "\n" + result.stderr.toString()

      at Object.<anonymous> (integration-tests/runIntegrationTest.ts:47:29)

  console.error src/spawnSafe.ts:24
    warning workspace-aggregator-23706d10-cf86-423f-b6e1-2b2f76df610e > a > left-pad@1.3.0: use String.prototype.padStart()
    warning /home/joe/patch-package/patch-package.test.1599467352.tgz > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    warning /home/joe/patch-package/patch-package.test.1599467352.tgz > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npx: installed 150 in 9.722s
    Error: spawnSync git ENOENT
        at Object.spawnSync (internal/child_process.js:1066:20)
        at Object.spawnSync (child_process.js:602:24)
        at Function.spawnSync [as sync] (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/node_modules/cross-spawn/index.js:26:23)
        at Object.exports.spawnSafeSync (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/spawnSafe.js:10:32)
        at git (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/makePatch.js:106:32)
        at Object.makePatch (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/makePatch.js:118:9)
        at /home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/index.js:48:25
        at Array.forEach (<anonymous>)
        at Object.<anonymous> (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/index.js:47:22)
        at Module._compile (internal/modules/cjs/loader.js:1075:30) {
      errno: -2,
      code: 'ENOENT',
      syscall: 'spawnSync git',
      path: 'git',
      spawnargs: [ 'init' ]
    }
    {
      error: Error: spawnSync git ENOENT
          at Object.spawnSync (internal/child_process.js:1066:20)
          at Object.spawnSync (child_process.js:602:24)
          at Function.spawnSync [as sync] (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/node_modules/cross-spawn/index.js:26:23)
          at Object.exports.spawnSafeSync (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/spawnSafe.js:10:32)
          at git (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/makePatch.js:106:32)
          at Object.makePatch (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/makePatch.js:118:9)
          at /home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/index.js:48:25
          at Array.forEach (<anonymous>)
          at Object.<anonymous> (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/index.js:47:22)
          at Module._compile (internal/modules/cjs/loader.js:1075:30) {
        errno: -2,
        code: 'ENOENT',
        syscall: 'spawnSync git',
        path: 'git',
        spawnargs: [ 'init' ]
      },
      status: null,
      signal: null,
      output: null,
      pid: 5749,
      stdout: null,
      stderr: null
    }
    undefined
    

  console.error integration-tests/runIntegrationTest.ts:53
    tarball /home/joe/patch-package/patch-package.test.1599467352.tgz
    add patch-package to root
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    success Saved lockfile.
    success Saved 69 new dependencies.
    info Direct dependencies
    └─ patch-package@0.0.0
    info All dependencies
    ├─ @yarnpkg/lockfile@1.1.0
    ├─ ansi-styles@3.2.1
    ├─ arr-flatten@1.1.0
    ├─ assign-symbols@1.0.0
    ├─ atob@2.1.2
    ├─ base@0.11.2
    ├─ braces@2.3.2
    ├─ cache-base@1.0.1
    ├─ chalk@2.4.2
    ├─ ci-info@2.0.0
    ├─ class-utils@0.3.6
    ├─ collection-visit@1.0.0
    ├─ color-convert@1.9.3
    ├─ color-name@1.1.3
    ├─ copy-descriptor@0.1.1
    ├─ debug@2.6.9
    ├─ decode-uri-component@0.2.0
    ├─ escape-string-regexp@1.0.5
    ├─ expand-brackets@2.1.4
    ├─ extglob@2.0.4
    ├─ fill-range@4.0.0
    ├─ find-yarn-workspace-root@1.2.1
    ├─ for-in@1.0.2
    ├─ fs-extra@7.0.1
    ├─ get-value@2.0.6
    ├─ graceful-fs@4.2.4
    ├─ has-flag@3.0.0
    ├─ has-value@1.0.0
    ├─ is-accessor-descriptor@1.0.0
    ├─ is-ci@2.0.0
    ├─ is-data-descriptor@1.0.0
    ├─ is-descriptor@1.0.2
    ├─ is-plain-object@2.0.4
    ├─ is-windows@1.0.2
    ├─ isarray@1.0.0
    ├─ kind-of@3.2.2
    ├─ klaw-sync@6.0.0
    ├─ map-visit@1.0.0
    ├─ micromatch@3.1.10
    ├─ minimist@1.2.5
    ├─ mixin-deep@1.3.2
    ├─ ms@2.0.0
    ├─ nanomatch@1.2.13
    ├─ object-copy@0.1.0
    ├─ os-tmpdir@1.0.2
    ├─ pascalcase@0.1.1
    ├─ patch-package@0.0.0
    ├─ posix-character-classes@0.1.1
    ├─ repeat-element@1.1.3
    ├─ resolve-url@0.2.1
    ├─ ret@0.1.15
    ├─ semver@5.7.1
    ├─ set-value@2.0.1
    ├─ slash@2.0.0
    ├─ snapdragon-node@2.1.1
    ├─ snapdragon-util@3.0.1
    ├─ source-map-resolve@0.5.3
    ├─ source-map-url@0.4.0
    ├─ source-map@0.5.7
    ├─ split-string@3.1.0
    ├─ static-extend@0.1.2
    ├─ supports-color@5.5.0
    ├─ tmp@0.0.33
    ├─ to-object-path@0.3.0
    ├─ to-regex-range@2.1.1
    ├─ union-value@1.0.1
    ├─ unset-value@1.0.0
    ├─ urix@0.1.0
    └─ use@3.1.1
    set up postinstall scripts
    modify hoisted left-pad
    node_modules/left-pad/index.js
     7: module.exports = patch-package;
     22: function patch-package (str, len, ch) {
    create patch file
    patch-package 0.0.0
    • Creating temporary folder
    • Installing left-pad@1.2.0 with yarn
    • Diffing your files with clean files
    ✔ Created file patches/left-pad+1.2.0.patch
    modify unhoisted left-pad
    packages/a/node_modules/left-pad/index.js
     7: module.exports = patch-package;
     22: function patch-package (str, len, ch) {
    create patch file
    patch-package 6.2.2
    • Creating temporary folder
    • Installing left-pad@1.3.0 with yarn
    • Diffing your files with clean files
    
    warning workspace-aggregator-23706d10-cf86-423f-b6e1-2b2f76df610e > a > left-pad@1.3.0: use String.prototype.padStart()
    warning /home/joe/patch-package/patch-package.test.1599467352.tgz > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    warning /home/joe/patch-package/patch-package.test.1599467352.tgz > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npx: installed 150 in 9.722s
    Error: spawnSync git ENOENT
        at Object.spawnSync (internal/child_process.js:1066:20)
        at Object.spawnSync (child_process.js:602:24)
        at Function.spawnSync [as sync] (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/node_modules/cross-spawn/index.js:26:23)
        at Object.exports.spawnSafeSync (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/spawnSafe.js:10:32)
        at git (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/makePatch.js:106:32)
        at Object.makePatch (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/makePatch.js:118:9)
        at /home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/index.js:48:25
        at Array.forEach (<anonymous>)
        at Object.<anonymous> (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/index.js:47:22)
        at Module._compile (internal/modules/cjs/loader.js:1075:30) {
      errno: -2,
      code: 'ENOENT',
      syscall: 'spawnSync git',
      path: 'git',
      spawnargs: [ 'init' ]
    }
    {
      error: Error: spawnSync git ENOENT
          at Object.spawnSync (internal/child_process.js:1066:20)
          at Object.spawnSync (child_process.js:602:24)
          at Function.spawnSync [as sync] (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/node_modules/cross-spawn/index.js:26:23)
          at Object.exports.spawnSafeSync (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/spawnSafe.js:10:32)
          at git (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/makePatch.js:106:32)
          at Object.makePatch (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/makePatch.js:118:9)
          at /home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/index.js:48:25
          at Array.forEach (<anonymous>)
          at Object.<anonymous> (/home/joe/.npm/_npx/5705/lib/node_modules/patch-package/dist/index.js:47:22)
          at Module._compile (internal/modules/cjs/loader.js:1075:30) {
        errno: -2,
        code: 'ENOENT',
        syscall: 'spawnSync git',
        path: 'git',
        spawnargs: [ 'init' ]
      },
      status: null,
      signal: null,
      output: null,
      pid: 5749,
      stdout: null,
      stderr: null
    }
    undefined
    

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        20.855s
Ran all test suites matching /.\/integration-tests\/yarn-workspaces\/yarn-workspaces.test.ts/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Digging through the logs, I've narrowed down the root-cause to this line.
https://github.com/ds300/patch-package/blob/50f73bdea03ebcd919b1497dd2be984b50e2861d/integration-tests/yarn-workspaces/yarn-workspaces.sh#L20-L22
I suspect `npx` simply downloads the *released* version of <samp>patch-package</samp> (which still has issue #181 #253)

Tests should use the *current/working* version? Not the one in the NPM registry.

**Comment by gomain** [comment]
It seems <samp>package/a/</samp> is supposedly a *sub-project*. With it own <samp>package.json</samp> and <samp>node_modules/</samp>. How was this to come about? Is it missing from this script?

**Comment by gomain** [comment]
OK, I've just learned about yarn [workspaces](https://classic.yarnpkg.com/en/docs/workspaces/) :smile: 

https://github.com/ds300/patch-package/blob/50f73bdea03ebcd919b1497dd2be984b50e2861d/integration-tests/yarn-workspaces/packages/a/package.json#L6-L8

I'm pretty sure all `npx patch-package ...` invocations were meant to be `yarn patch-package ...` invocationss. It wouldn't make sense otherwise. Doing so enables passing of the test!

I can make a PR for this.

This includes the invocation at
https://github.com/ds300/patch-package/blob/50f73bdea03ebcd919b1497dd2be984b50e2861d/integration-tests/yarn-workspaces/yarn-workspaces.sh#L14-L15
also is supposed to be `yarn patch-package left-pad`? But here, `npx` just happens to work.

**Comment by gomain** [comment]
I've noticed in all other <samp>integration-tests/</samp> `npx` is preferred over `yarn` when invoking <samp>patch-package</samp>. Can someone explain to me why this is the case?

**Comment by gomain** [comment]
@ds300
