### ISSUE TITLE
patch-package fails when .yarnrc sets yarn-path

### ISSUE THREAD

**Issue by lstrojny** [ds300/patch-package#291]
Given this `.yarnrc`:

```
yarn-path "./yarn"
```

`patch-package some-package` will fail to generate a patch with this error message:

```
• Creating temporary folder
• Installing … with yarn
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/…/yarn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by almeidx** [comment]
Can repro 
```
patch-package 6.2.2
• Creating temporary folder
• Installing ... with yarn
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\...\AppData\Local\Temp\tmp-...\.yarn\releases\yarn-1.22.10.cjs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by lstrojny** [comment]
For what it's worth, I used `./node_modules/.bin/patch-package` directly.
