### ISSUE TITLE
[npm] Support lockfile version 3

### ISSUE THREAD

**Issue by brettwillis** [ds300/patch-package#393]
Since NPM version 7, the package-lock.json version 2 file now uses a `packages` field, and the `dependencies` field is duplicated for backwards compatibility.

It is possible to configure NPM to use a package-lock.json version 3, which omits the `dependencies` field to greatly reduce the size of the lock file. See https://docs.npmjs.com/cli/v8/using-npm/config#lockfile-version.

To support `lockfile-version=3`, patch-package must be able to interpret the `packages` field of the lock file.

**Comment by orta** [comment]
Sure, open to PRs on this 👍🏻

**Comment by quicksilverr** [comment]
Can anyone explain, why this TypeError: Cannot read properties of undefined (reading 'dependencies') when trying to run npx patch-package error, is coming? 

I'm unable to understand it.

**Comment by ryaa** [comment]
> Can anyone explain, why this TypeError: Cannot read properties of undefined (reading 'dependencies') when trying to run npx patch-package error, is coming?
> 
> I'm unable to understand it.

The **package-lock.json** lockVersion 3 has different format than version 2. Specifically, "dependencies" node is not present as one of the top nodes in **package-lock.json**. The **patch-package** expect it to be there and fails when it is missing.

**Comment by quicksilverr** [comment]
And this also happens with yarn as well?

> > Can anyone explain, why this TypeError: Cannot read properties of undefined (reading 'dependencies') when trying to run npx patch-package error, is coming?
> > I'm unable to understand it.
> 
> The **package-lock.json** lockVersion 3 has different format than version 2. Specifically, "dependencies" node is not present as one of the top nodes in **package-lock.json**. The **patch-package** expect it to be there and fails when it is missing.

**Comment by quicksilverr** [comment]
when I am doing yarn patch-package <package> it's throwing the error.

**Comment by anas10** [comment]
I've opened a PR to solve this issue here: https://github.com/ds300/patch-package/pull/434
I've tested it locally and it works fine. I've made the change in a way that should make it compatible with all versions of lockfile.

**Comment by Samuel-Therrien-Beslogic** [comment]
This is happening to me with `patch-package 7.0.0` and `patch-package 8.0.0` on `Node.js v18.14.0` with a `"lockfileVersion": 3`:

```
npx patch-package localForage 
patch-package 8.0.0
• Creating temporary folder
TypeError: Cannot read properties of undefined (reading 'dependencies')
    at Object.getPackageResolution (...\node_modules\patch-package\dist\getPackageResolution.js:98:40)
    at Object.makePatch (...\node_modules\patch-package\dist\makePatch.js:103:63)
    at ...\node_modules\patch-package\dist\index.js:72:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (...\node_modules\patch-package\dist\index.js:71:22)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
...\node_modules\patch-package\dist\makePatch.js:395
        throw e;
        ^

TypeError: Cannot read properties of undefined (reading 'dependencies')
    at Object.getPackageResolution (...\node_modules\patch-package\dist\getPackageResolution.js:98:40)
    at Object.makePatch (...\node_modules\patch-package\dist\makePatch.js:103:63)
    at ...\node_modules\patch-package\dist\index.js:72:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (...\node_modules\patch-package\dist\index.js:71:22)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)

Node.js v18.14.0
```

**Comment by alohaninja** [comment]
Upgrading from `patch-package` 6.4.7 to 8.0.0 resolved this error for us!

> TypeError: Cannot read properties of undefined (reading 'dependencies')
