### ISSUE TITLE
Problem error in patch d-danfe

### ISSUE THREAD

**Issue by jtairone** [ds300/patch-package#442]
I'm trying to do the npx patch-package d-danfe and I get this error:

npx patch-package d-danfe
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
patch-package 6.5.0
• Creating temporary folder
• Installing d-danfe@2.0.0 with npm
• Diffing your files with clean files
Error: ENOENT: no such file or directory, scandir 'C:\Users\TECNOL~1\AppData\Local\Temp\tmp-190444nNSXAGP5h8c\node_modules\d-danfe'
    at Object.readdirSync (node:fs:1405:3)
    at Object.klawSync [as default] (C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\klaw-sync\klaw-sync.js:13:25)
    at Object.removeIgnoredFiles (C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\patch-package\dist\filterFiles.js:11:24)
    at Object.makePatch (C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\patch-package\dist\makePatch.js:121:23)
    at C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\patch-package\dist\index.js:53:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\patch-package\dist\index.js:52:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\TECNOL~1\\AppData\\Local\\Temp\\tmp-190444nNSXAGP5h8c\\node_modules\\d-danfe'
}
C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\patch-package\dist\makePatch.js:218
        throw e;
        ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\TECNOL~1\AppData\Local\Temp\tmp-190444nNSXAGP5h8c\node_modules\d-danfe'
    at Object.readdirSync (node:fs:1405:3)
    at Object.klawSync [as default] (C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\klaw-sync\klaw-sync.js:13:25)
    at Object.removeIgnoredFiles (C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\patch-package\dist\filterFiles.js:11:24)
    at Object.makePatch (C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\patch-package\dist\makePatch.js:121:23)
    at C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\patch-package\dist\index.js:53:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\tecnologia\Documents\Projetos\api_portalcli_macrolub\node_modules\patch-package\dist\index.js:52:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\TECNOL~1\\AppData\\Local\\Temp\\tmp-190444nNSXAGP5h8c\\node_modules\\d-danfe'
}

this package in pacckage.json looks like this "d-danfe": "github:douglasselias/djf-danfe" I believe it is published in gitgub could that be why the problem? I tried the commands reported in the documentation but it didn't work.

If you can help me what can I do to fix it and be able to use your tool because it will help me a lot, thank you in advance for your help!.

**Comment by YasharF** [comment]
I think patching individual packages is out of the scope for this repo.
