### ISSUE TITLE
Can't patch package- fails with status 1, no error

### ISSUE THREAD

**Issue by tlangston23** [ds300/patch-package#484]
Hi I'm still getting the below error even though it was allegedly fixed in an earlier version:

C:\TMAX-R\trunk\lucid_client>npx patch-package @inovua/reactdatagrid-enterprise
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
patch-package 8.0.0
• Creating temporary folder
• Installing @inovua/reactdatagrid-enterprise@5.9.2 with npm
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 24900,
  stdout: null,
  stderr: null,
  error: null
}

C:\TMAX-R\trunk\lucid_client\node_modules\patch-package\dist\makePatch.js:395
        throw e;
        ^
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 24900,
  stdout: null,
  stderr: null,
  error: null
}

**Comment by quolpr** [comment]
Same issue:

```
npx patch-package  snabbdom
patch-package 8.0.0
• Creating temporary folder
• Installing snabbdom@0.7.3 with yarn

{
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 1b 5b 33 31 6d 1b 5b 31 6d 55 6e 6b 6e 6f 77 6e 20 53 79 6e 74 61 78 20 45 72 72 6f 72 1b 5b 32 32 6d 1b 5b 33 39 6d 3a 20 55 6e 73 75 70 70 6f 72 74 ... 142 more bytes>,
    <Buffer >
  ],
  pid: 77815,
  stdout: <Buffer 1b 5b 33 31 6d 1b 5b 31 6d 55 6e 6b 6e 6f 77 6e 20 53 79 6e 74 61 78 20 45 72 72 6f 72 1b 5b 32 32 6d 1b 5b 33 39 6d 3a 20 55 6e 73 75 70 70 6f 72 74 ... 142 more bytes>,
  stderr: <Buffer >,
  error: null
}

/Users/quolpr/.npm/_npx/1a782c0cdc01f9d4/node_modules/patch-package/dist/makePatch.js:395
        throw e;
        ^
{
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(192) [Uint8Array] [
       27,  91,  51,  49, 109,  27,  91,  49, 109,  85, 110, 107,
      110, 111, 119, 110,  32,  83, 121, 110, 116,  97, 120,  32,
       69, 114, 114, 111, 114,  27,  91,  50,  50, 109,  27,  91,
       51,  57, 109,  58,  32,  85, 110, 115, 117, 112, 112, 111,
      114, 116, 101, 100,  32, 111, 112, 116, 105, 111, 110,  32,
      110,  97, 109, 101,  32,  40,  34,  45,  45, 105, 103, 110,
      111, 114, 101,  45, 115,  99, 114, 105, 112, 116, 115,  34,
       41,  46,  10,  10,  36,  32, 121,  97, 114, 110,  32, 105,
      110, 115, 116,  97,
      ... 92 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 77815,
  stdout: Buffer(192) [Uint8Array] [
     27,  91,  51,  49, 109,  27,  91,  49, 109,  85, 110, 107,
    110, 111, 119, 110,  32,  83, 121, 110, 116,  97, 120,  32,
     69, 114, 114, 111, 114,  27,  91,  50,  50, 109,  27,  91,
     51,  57, 109,  58,  32,  85, 110, 115, 117, 112, 112, 111,
    114, 116, 101, 100,  32, 111, 112, 116, 105, 111, 110,  32,
    110,  97, 109, 101,  32,  40,  34,  45,  45, 105, 103, 110,
    111, 114, 101,  45, 115,  99, 114, 105, 112, 116, 115,  34,
     41,  46,  10,  10,  36,  32, 121,  97, 114, 110,  32, 105,
    110, 115, 116,  97,
    ... 92 more items
  ],
  stderr: Buffer(0) [Uint8Array] [],
  error: null
}

```

**Comment by shukerullah** [comment]
Same

**Comment by facetious** [comment]
This happened to me when the registry listed in my package-lock.json didn't match the registry in my .npmrc.

**Comment by eeshankeni** [comment]
This has been happening to me as well all of a sudden

**Comment by hwride** [comment]
I still get the problem using `npx patch-package`. We're using a private registry as well, so could be related.

**Comment by pep108** [comment]
I had the same problem, even when using `npx patch-package`. what solved it for me was to switch from node v21.6.2
to version to 17.7.2.

**Comment by cdavie-artium** [comment]
Neither downgrading node nor `.npmrc` configurations fixed this error for me.

**Comment by fatinfarzanaazizan** [comment]
> Neither downgrading node nor `.npmrc` configurations fixed this error for me.

same here. i tried downgrading yarn ( from berry to classic) but doesn't work either

**Comment by fatinfarzanaazizan** [comment]
after a few tries, what worked for me was to downgrade yarn (from berry to yarn 1)  AND to downgrade node version to 17 (16 and 20 don't work for some reason).

**Comment by daem0ndev** [comment]
for me the issue was that i was patching a package in node_modules but it was not explicitly in my repo's package.json (it was a resolved dependency from another package) once I added it to my repo's package.json npx patch-package worked fine.

**Comment by orionna319** [comment]
Same issue:

macOS Sequola 15.0
Node version v14.21.3

```sh
npm install patch-package --save
npx patch-package uview-ui

• Creating temporary folder
• Installing uview-ui@1.8.4 with npm
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 52048,
  stdout: null,
  stderr: null,
  error: null
}
```

**Comment by nagendra-d** [comment]
> Same issue:
> 
> macOS Sequola 15.0 Node version v14.21.3
> 
> ```shell
> npm install patch-package --save
> npx patch-package uview-ui
> 
> • Creating temporary folder
> • Installing uview-ui@1.8.4 with npm
> {
>   status: 1,
>   signal: null,
>   output: [ null, null, null ],
>   pid: 52048,
>   stdout: null,
>   stderr: null,
>   error: null
> }
> ```

Had a similar issue, trying with `sudo` worked

**Comment by ahmad6242** [comment]
same issue
    "postinstall-postinstall": "^2.1.0",
    "patch-package": "^8.0.1",
    "react": "19.0.0",
    "react-native": "0.78.1",
node v23.9.0

```
patch-package 8.0.1
• Creating temporary folder
• Installing react-native-compressor@1.13.0 with yarn

{
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 1b 5b 33 31 6d 1b 5b 31 6d 55 6e 6b 6e 6f 77 6e 20 53 79 6e 74 61 78 20 45 72 72 6f 72 1b 5b 32 32 6d 1b 5b 33 39 6d 3a 20 55 6e 73 75 70 70 6f 72 74 ... 142 more bytes>,
    <Buffer >
  ],
  pid: 25414,
  stdout: <Buffer 1b 5b 33 31 6d 1b 5b 31 6d 55 6e 6b 6e 6f 77 6e 20 53 79 6e 74 61 78 20 45 72 72 6f 72 1b 5b 32 32 6d 1b 5b 33 39 6d 3a 20 55 6e 73 75 70 70 6f 72 74 ... 142 more bytes>,
  stderr: <Buffer >,
  error: null
}

/Volumes/EducoreKing/React-Native/EducoreTeacher/node_modules/patch-package/dist/makePatch.js:395
        throw e;
        ^
{
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(192) [Uint8Array] [
       27,  91,  51,  49, 109,  27,  91,  49, 109,  85, 110, 107,
      110, 111, 119, 110,  32,  83, 121, 110, 116,  97, 120,  32,
       69, 114, 114, 111, 114,  27,  91,  50,  50, 109,  27,  91,
       51,  57, 109,  58,  32,  85, 110, 115, 117, 112, 112, 111,
      114, 116, 101, 100,  32, 111, 112, 116, 105, 111, 110,  32,
      110,  97, 109, 101,  32,  40,  34,  45,  45, 105, 103, 110,
      111, 114, 101,  45, 115,  99, 114, 105, 112, 116, 115,  34,
       41,  46,  10,  10,  36,  32, 121,  97, 114, 110,  32, 105,
      110, 115, 116,  97,
      ... 92 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 25414,
  stdout: Buffer(192) [Uint8Array] [
     27,  91,  51,  49, 109,  27,  91,  49, 109,  85, 110, 107,
    110, 111, 119, 110,  32,  83, 121, 110, 116,  97, 120,  32,
     69, 114, 114, 111, 114,  27,  91,  50,  50, 109,  27,  91,
     51,  57, 109,  58,  32,  85, 110, 115, 117, 112, 112, 111,
    114, 116, 101, 100,  32, 111, 112, 116, 105, 111, 110,  32,
    110,  97, 109, 101,  32,  40,  34,  45,  45, 105, 103, 110,
    111, 114, 101,  45, 115,  99, 114, 105, 112, 116, 115,  34,
     41,  46,  10,  10,  36,  32, 121,  97, 114, 110,  32, 105,
    110, 115, 116,  97,
    ... 92 more items
  ],
  stderr: Buffer(0) [Uint8Array] [],
  error: null
}

Node.js v23.9.0
```

**Comment by marcincichocki** [comment]
I had same issue when working in repo with private registry set up. But, I needed to patch package from default npm registry. I fixed it by patching patch-package(no pun intended). I added default registry to npm install call:

*node_modules/patch-package/dist/makePatch.js:141*
```
                spawnSafe_1.spawnSafeSync(`npm`, ["i", "--force", "--registry=https://registry.npmjs.org/"], {
```

and successfully patched the package.


I also have an idea what might be going on. I removed options in that call, and the error message indicated that 404 status code was returned because of missing path to the registry. In my case it was:

```
https://<private_registry_hostname>/@stencil/store/-/store-2.1.3.tgz
```

but it should've been:

```
https://<private_registry_hostname>/<private_registry_pathname>/@stencil/store/-/store-2.1.3.tgz
```

**Comment by ZandercraftGames** [comment]
Nothing seems to be working for me. Not the versioning or the patches.

On Node 22:
```
$ patch-package typeorm
patch-package 8.0.1
• Creating temporary folder
• Installing typeorm@0.3.28 with yarn

{
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 1b 5b 33 31 6d 1b 5b 31 6d 55 6e 6b 6e 6f 77 6e 20 53 79 6e 74 61 78 20 45 72 72 6f 72 1b 5b 32 32 6d 1b 5b 33 39 6d 3a 20 55 6e 73 75 70 70 6f 72 74 ... 185 more bytes>,
    <Buffer >
  ],
  pid: 48656,
  stdout: <Buffer 1b 5b 33 31 6d 1b 5b 31 6d 55 6e 6b 6e 6f 77 6e 20 53 79 6e 74 61 78 20 45 72 72 6f 72 1b 5b 32 32 6d 1b 5b 33 39 6d 3a 20 55 6e 73 75 70 70 6f 72 74 ... 185 more bytes>,
  stderr: <Buffer >,
  error: null
}

D:\WebstormProjects\FOX\node_modules\patch-package\dist\makePatch.js:395
        throw e;
        ^
{
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(235) [Uint8Array] [
       27,  91,  51,  49, 109,  27,  91,  49, 109,  85, 110, 107,
      110, 111, 119, 110,  32,  83, 121, 110, 116,  97, 120,  32,
       69, 114, 114, 111, 114,  27,  91,  50,  50, 109,  27,  91,
       51,  57, 109,  58,  32,  85, 110, 115, 117, 112, 112, 111,
      114, 116, 101, 100,  32, 111, 112, 116, 105, 111, 110,  32,
      110,  97, 109, 101,  32,  40,  34,  45,  45, 105, 103, 110,
      111, 114, 101,  45, 115,  99, 114, 105, 112, 116, 115,  34,
       41,  46,  10,  10,  36,  32, 121,  97, 114, 110,  32, 105,
      110, 115, 116,  97,
      ... 135 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 48656,
  stdout: Buffer(235) [Uint8Array] [
     27,  91,  51,  49, 109,  27,  91,  49, 109,  85, 110, 107,
    110, 111, 119, 110,  32,  83, 121, 110, 116,  97, 120,  32,
     69, 114, 114, 111, 114,  27,  91,  50,  50, 109,  27,  91,
     51,  57, 109,  58,  32,  85, 110, 115, 117, 112, 112, 111,
    114, 116, 101, 100,  32, 111, 112, 116, 105, 111, 110,  32,
    110,  97, 109, 101,  32,  40,  34,  45,  45, 105, 103, 110,
    111, 114, 101,  45, 115,  99, 114, 105, 112, 116, 115,  34,
     41,  46,  10,  10,  36,  32, 121,  97, 114, 110,  32, 105,
    110, 115, 116,  97,
    ... 135 more items
  ],
  stderr: Buffer(0) [Uint8Array] [],
  error: null
}

Node.js v22.19.0
```

On Node 17:
```
$ patch-package typeorm
patch-package 8.0.1
• Creating temporary folder
• Installing typeorm@0.3.28 with yarn
• Diffing your files with clean files
⁉️  Not creating patch file for package 'typeorm'
⁉️  There don't appear to be any changes.
```

**Edit:** Secondary issue is #492

**Comment by VaslD** [comment]
Saw this today.

`patch-package` downloads respective packages in a temporary project (directory) and diffs with modified ones in your project.

For those that:

- Lock a particular version of `yarn` with `packageManager`; and/or
- Use a project-level `.yarnrc.yml` that differs from global config

`patch-package` will fail because configurations are not carried over to the temporary project.

Use the following patch on `patch-package`: 🤷‍♂️

```diff
@@ -0,0 +1,16 @@
diff --git a/node_modules/patch-package/dist/makePatch.js b/node_modules/patch-package/dist/makePatch.js
index d8d0925..55d85d9 100644
--- a/node_modules/patch-package/dist/makePatch.js
+++ b/node_modules/patch-package/dist/makePatch.js
@@ -107,9 +107,10 @@ function makePatch({ packagePathSpecifier, appPath, packageManager, includePaths
                 }),
             },
             resolutions: resolveRelativeFileDependencies_1.resolveRelativeFileDependencies(appPath, appPackageJson.resolutions || {}),
+            packageManager: appPackageJson.packageManager,
         }));
         const packageVersion = getPackageVersion_1.getPackageVersion(path_1.join(path_1.resolve(packageDetails.path), "package.json"));
-        [".npmrc", ".yarnrc", ".yarn"].forEach((rcFile) => {
+        [".npmrc", ".yarnrc", ".yarn", ".yarnrc.yml"].forEach((rcFile) => {
             const rcPath = path_1.join(appPath, rcFile);
             if (fs_extra_1.existsSync(rcPath)) {
                 fs_extra_1.copySync(rcPath, path_1.join(tmpRepo.name, rcFile), { dereference: true });
```

**Comment by denilsonsa** [comment]
These lines are re-throwing the exception, and thus they are masking the actual exception cause:

https://github.com/ds300/patch-package/blob/be4dfd77d941c0e6fb56b60843f3a98fd1d7ba4c/src/makePatch.ts#L547-L549

If I comment them out, I get this error instead:

```
/home/foobar/fooproject/node_modules/patch-package/dist/spawnSafe.js:22
            throw result;
            ^
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 37923,
  stdout: null,
  stderr: null,
  error: null
}
```

Which maps to this code:

https://github.com/ds300/patch-package/blob/be4dfd77d941c0e6fb56b60843f3a98fd1d7ba4c/src/spawnSafe.ts#L31

Since it is throwing something that is NOT an `Error` object, we don't get the actual stack trace. Replacing that line with:

```js
            throw new Error(JSON.stringify(result, null, 2));
```

Prints a more descriptive error message:

```
    at Object.spawnSafeSync (/home/foobar/fooproject/node_modules/patch-package/dist/spawnSafe.js:22:19)
    at Object.makePatch (/home/foobar/fooproject/node_modules/patch-package/dist/makePatch.js:149:29)
    at /home/foobar/fooproject/node_modules/patch-package/dist/index.js:72:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/foobar/fooproject/node_modules/patch-package/dist/index.js:71:22)
    at Module._compile (node:internal/modules/cjs/loader:1854:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1985:10)
    at Module.load (node:internal/modules/cjs/loader:1577:32)
    at Module._load (node:internal/modules/cjs/loader:1379:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
```

Which in my case is an error when running `npm i --force`. When I run that manually, I get a helpful error message from npm, printed to stderr. However, somehow this error message is lost in this case, and thus it is not printed. I don't understand why.

In any case, now I know why it was throwing an error for me today.

---

Recommendation to the maintainer of `patch-package`:

* Avoid throwing things that are NOT derived from `Error`. Replace those cases with an instance of `Error`, so that we can get proper stack traces.

**Comment by lppedd** [comment]
For posterity, disable `min-release-age` when creating patches.
