### ISSUE TITLE
Package creation fails on Windows (command cp doesn't exist)

### ISSUE THREAD

**Issue by ashmind** [ds300/patch-package#7]
```
Error: Command failed: cp '[REDACTED]\WebApp\package.json' 'C:\Users\Andrey\AppData\Local\Temp\tmp-67620GzG5P14Xw1BW'
'cp' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:568:13)
    at Object.execSync (child_process.js:608:13)
    at Object.makePatch [as default] ([REDACTED]\WebApp\node_modules\patch-package\dist\makePatch.js:42:25)
    at [REDACTED]\WebApp\node_modules\patch-package\dist\index.js:20:32
    at Array.forEach (native)
    at Object.<anonymous> ([REDACTED]\WebApp\node_modules\patch-package\dist\index.js:19:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

**Comment by ds300** [comment]
Thanks for the report. I'll look into cross-platform copy utils.

**Comment by ds300** [comment]
![image](https://user-images.githubusercontent.com/1242537/28977974-1686fd26-793c-11e7-965c-f77620784783.png)

**Comment by ashmind** [comment]
Awesome -- thanks a lot!
Still getting some issues with `path.join` vs slashes that git expects, but I'll raise that separately.
