### ISSUE TITLE
patch-package fails if postinstall script calls script calls local script

### ISSUE THREAD

**Issue by n1ru4l** [ds300/patch-package#77]
When using `patch-package` with the following postinstall script the process of creating a patch fails. This is most likely due to the fact that patch-package only copies the `package.json`.

```js
"postinstall": "react-native-schemes-manager all && node ./scripts/dotenv-setup.js",
```

```
yarn patch-package appcenter
```

```
module.js:549
    throw err;
    ^

Error: Cannot find module '/private/var/folders/1h/wxvhv6_52lb7yqsy3htvp_mc0000gn/T/tmp-63091FLj59aIQdL5c/scripts/dotenv-setup.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
```

Possible solutions: 

- Copy whole directory
- Prevent postinstall script from running when patching a package

I would love to help out if someone can point me into the direction this case should be handled

**Comment by msand** [comment]
I had a similar issue with a postinstall script running solidarity, when used with yarn, it just gave "Command failed with exit code 3" and a few buffers as output. Removed node_modules and yarn.lock, installed with npm, ran again, and got:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! ProjectName@0.0.1 postinstall: `solidarity`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the ProjectName@0.0.1 postinstall script.
```
Renamed the postinstall to postinstalls, and patch-package worked fine.

**Comment by cjhill00** [comment]
> Hi 👋 Thanks for the report! I've been aware of this issue for a while. It is fixed it by excluding the package.json's scripts entry when creating a patch file. The patch-package@beta release includes this fix, you can use that if you like.
> 
> I'll close this issue for now, but please let me know if the beta release didn't work out.

I can't find this beta release, @ds300. Could you send me the link?
