### ISSUE TITLE
Custom git path(s) based on environment

### ISSUE THREAD

**Issue by ivikash** [ds300/patch-package#90]
Hi, I have a project which is being built on multiple environments with multiple git paths. In some environments, it is throwing the following error. 
```
**ERROR** patch-package requires Git

Please make sure that git is available in all of the necessary environments for your project.
``` 

Is there a way in which I can pass custom paths and make the builds pass?

**Comment by ds300** [comment]
Not right now, but the `patch-package@beta` releases should not require git for applying patches, so you could try using those

**Comment by ivikash** [comment]
Thanks @ds300. I did try it and now I am receiving the following error.

```
module.js:550
    throw err;
    ^
Error: Cannot find module './dist/index.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/local/home/<someFolderPath>:12:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myPackage@1.0.0 prepare: `patch-package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myPackage@1.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vikasagr/.npm/_logs/2018-10-17T17_51_13_078Z-debug.log
BUILD FAILED

```

**Comment by ds300** [comment]
Oh no that looks bad 😬you might try the next-most-recent release `patch-package@6.0.0-9`

**Comment by ds300** [comment]
I can't reproduce that error, do you mind letting me know a bit more about the environment patch-package is running in? OS, node version, any other info you think might be relevant?

**Comment by ivikash** [comment]
`6.0.0-5` seems to be working for me. But getting the following error.


```
> patch-package
patch-package: Applying patches...
**ERROR** Failed to apply patch for package somePackage
  This error was caused because patch-package cannot apply the following patch file:
    patches/somePackage+0.10.0.patch
  If removing node_modules and trying again doesn't fix this, maybe there was
  an accidental change made to the patch file? If not, then it's probably a bug
  in patch-package, so please submit a bug report. Thanks!
    https://github.com/ds300/patch-package/issues
```

**Comment by ivikash** [comment]
Created new patches and it works.
